// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xK9jlwNHpzXluIWAeozJv0_p_uc1YQs',
    appId: '1:1091410814765:web:6b44960bf9192ead4595a4',
    messagingSenderId: '1091410814765',
    projectId: 'flutter-mmd',
    authDomain: 'flutter-mmd.firebaseapp.com',
    databaseURL: 'https://flutter-mmd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-mmd.appspot.com',
    measurementId: 'G-4Q9G567F67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2cA-bi4qQRKaBRCI8fVN5J9fjd9biQU',
    appId: '1:1091410814765:android:1b570fe98525f5414595a4',
    messagingSenderId: '1091410814765',
    projectId: 'flutter-mmd',
    databaseURL: 'https://flutter-mmd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-mmd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOJ2oB2zDXNSr2Z5_5kf-j5gd05mt-Z0',
    appId: '1:1091410814765:ios:62c69623719cc62f4595a4',
    messagingSenderId: '1091410814765',
    projectId: 'flutter-mmd',
    databaseURL: 'https://flutter-mmd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-mmd.appspot.com',
    iosBundleId: 'com.example.sewingInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOJ2oB2zDXNSr2Z5_5kf-j5gd05mt-Z0',
    appId: '1:1091410814765:ios:62c69623719cc62f4595a4',
    messagingSenderId: '1091410814765',
    projectId: 'flutter-mmd',
    databaseURL: 'https://flutter-mmd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-mmd.appspot.com',
    iosBundleId: 'com.example.sewingInformation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4xK9jlwNHpzXluIWAeozJv0_p_uc1YQs',
    appId: '1:1091410814765:web:d19f641c77423c934595a4',
    messagingSenderId: '1091410814765',
    projectId: 'flutter-mmd',
    authDomain: 'flutter-mmd.firebaseapp.com',
    databaseURL: 'https://flutter-mmd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-mmd.appspot.com',
    measurementId: 'G-RFHR1J73ZX',
  );
}
